### ISSUE TITLE
In workflow graph, the text on the link can't be wrapped by <br/> tag if the link is styled explicitly by linkStyle in the code

### ISSUE THREAD

**Issue by georgelichen** [mermaid-js/mermaid#1088]
In workflow graph, the text on the link can be wrapped by <br/> tags in the text.  Here is an example code:

```
graph LR
A[Task1<br/>Line2] -->|Text<br/>Line2| B(Task2<br/>Line2)
```

Live editor url:
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBBW1Rhc2sxPGJyLz5MaW5lMl0gLS0-fFRleHQ8YnIvPkxpbmUyfCBCKFRhc2syPGJyLz5MaW5lMikiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

But, if this link is styled by linkStyle in the code, the `<br/>` will be explained as a plain text rather than carriage return.  Here is an example code:

```
graph LR
A[Task1<br/>Line2] -->|Text<br/>Line2| B(Task2<br/>Line2)
linkStyle 0 stroke:DarkGray,stroke-width:2px
```

Live editor url:
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBBW1Rhc2sxPGJyLz5MaW5lMl0gLS0-fFRleHQ8YnIvPkxpbmUyfCBCKFRhc2syPGJyLz5MaW5lMilcblxubGlua1N0eWxlIDAgc3Ryb2tlOkRhcmtHcmF5LHN0cm9rZS13aWR0aDoycHgiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

**Comment by GDFaber** [comment]
My first guess (without further investigation) is that replacing <br/> does not work in that case because the regex search expects <br> to be used. But <br> seems to be automatically completed to <br/> when creating the flowchart, which I have just tested in the live editor.

If that is correct, the regular expression could be modified to solve the problem. I can take a look at it during the week if that's alright with you.

**Comment by GDFaber** [comment]
This can be solved by changing the regular expression from ```/<br>/g``` to ```/<br ?\/?>/g``` to catch ```<br>``` as well as ```<br/>``` and ```<br />```.

**Comment by GDFaber** [comment]
My PR is at #1132.
