### ISSUE TITLE
Class diagram specify return type

### ISSUE THREAD

**Issue by IceflowRE** [mermaid-js/mermaid#1119]
At the moment i didnt found a way to specify a return value/type from a funtion
```
classDiagram
class Foo{
- counter : int
+ do(work: int) : error
}
```

It will only be put in the right place if it has a `)` at the end

**Comment by chris579** [comment]
Right, that's a known limitation I'm also not happy with. However, I don't see a better way of detecting if something is a method than just looking for a closed brace in the end. The alternative would be to do some regex stuff which could be error prone.

**Comment by jgreywolf** [comment]
We _could_ always do something similar to PlantUML.  They have an option to explicitly define a member as `{field}` or `{method}'

Or we could just wrap return type in `{}` after the closing brace..

```
methodName(int id) {returns}
```

**Comment by jgreywolf** [comment]
On second thought - how should this look?  Because right now you can do this...  sort of

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5DbGFzczAxIDx8LS0gQXZlcnlMb25nQ2xhc3MgOiBDb29sXG48PGludGVyZmFjZT4-IENsYXNzMDFcbkNsYXNzMDEgOiBpbnQgc2l6ZSgpXG5DbGFzczAxIDogaW50IGNoaW1wXG5DbGFzczAxIDogaW50IGdvcmlsbGEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

**Comment by chris579** [comment]
> We _could_ always do something similar to PlantUML. They have an option to explicitly define a member as `{field}` or `{method}'
> 
> Or we could just wrap return type in `{}` after the closing brace..
> 
> ```
> methodName(int id) {returns}
> ```
Going with PlantUML sounds reasonable, however I don't like their syntax. Wrapping this in brackets could be convenient.


> On second thought - how should this look? Because right now you can do this... sort of

That's right, but this is not the official syntax for return values or data types.
