### ISSUE TITLE
Is there a way to build / transpile mermaidAPI for ES5?

### ISSUE THREAD

**Issue by blizzardengle** [mermaid-js/mermaid#1122]
I am a novice when it comes to webpack and babel. I tried my best at changing the webpack files to build the `mermaidAPI.js` but it still left require statements in the compiled code.

Is it possible to build `mermaidAPI.js` into a single ES5 file?

**Comment by chris579** [comment]
For now we use [babel preset environment](https://babeljs.io/docs/en/babel-preset-env) which does the ES-Version micromanagement for us. It's targeting the [majority of web browsers](https://github.com/mermaid-js/mermaid/blob/master/babel.config.js#L6) including `IE11` for example. I don't really understand what you try to achieve and what you did in particular. Could you elaborate more on what's your actual problem? Are you installing mermaid with `npm` / `yarn` or are you using the `unpkg` CDN?

**Comment by blizzardengle** [comment]
I am using a markdown parser for an application and it does not support diagrams of any kind. A long time ago I hacked in a solution where it would use `mermaid` to do that. Now that I'm looking to update the application I noticed that `mermaid` has grown and the newest version recommends that I use `mermaidAPI.js` for what I'm doing instead of `mermaid.js` or `mermaid-core.js`.

The markdown parser works in a top down loop. On set intervals it runs through what the user has typed and updates a live HTML preview. In the past if markdown for diagrams was encountered a DIV with a notice was put in its place letting the user know they don't support diagrams; in case you copied and pasted one in. I removed that part of the code and put the calls to mermaid there.

When I cloned the latest repo and compiled with the build command (npm run build) `mermaidAPI.js` was not in the `dist` folder. I can see it in the `src` folder but it appears it was not built for deployment as a single file. What I'm trying to do is get a copy of the compiled single file `mermaidAPI.js` that supports as many browsers as possible.

Again I am a novice when it comes to webpack and babel; this is my first attempt at every using them novice.

**Comment by chris579** [comment]
I assume you already visited our [installation guide](https://mermaid-js.github.io/mermaid/#/usage).

> Now that I'm looking to update the application I noticed that mermaid has grown and the newest version recommends that I use mermaidAPI.js

I think you are referring to this statement in the docs:

> Warning This type of integration is deprecated. Instead the preferred way of handling more complex integration is to use the mermaidAPI instead.

That warning is right. `mermaid` more or less is just a wrapper around `mermaidAPI` and I would always favour for using the latter one because the first one is just legacy stuff.
However, [here in the docs](https://mermaid-js.github.io/mermaid/#/usage?id=api-usage) an obscure `mermaidAPI.js` is mentioned I've never seen before. I'm quite sure that the docs are outdated.

For installing you have two options like described in the installation guide. Either [npm](https://www.npmjs.com/package/mermaid) which I would recommend if you have a js app that get's compiled via webpack or otherwise [unpkg](https://unpkg.com/browse/mermaid@8.4.3/dist/) which has the latest compiled mermaid versions. You don't need to compile by yourself. As already mentioned, mermaid ships for all major browsers (even including Internet Explorer which should die fast and horribly) and doesn't need any polyfills. Just use the `mermaid.min.js` and you're good to go.

**Comment by blizzardengle** [comment]
Thank you! Your right, the documentation was leading me astray. I used `mermaid.render(...)` and its all working again.

**Comment by Dunning-Kruger** [comment]
@blizzardengle Don't forget to close the issue it it was solved! Thank you for reaching out!
