### ISSUE TITLE
Flow diagram DB shape request

### ISSUE THREAD

**Issue by mgood2** [mermaid-js/mermaid#1154]
**Is your feature request related to a problem? Please describe.**

I'm requesting for a DB symbol in the flowchart.

**Describe the solution you'd like**
graph LR
    id1[(This is the text in the box)]
creates 
database symbol

**Describe alternatives you've considered**

**Additional context**

**Comment by GDFaber** [comment]
I wanted to know if this is already possible by just adding a new shape and ended up with a prototype (I asked Google about cylindrical shapes in SVG and was pointed to using a ```path``` element).

Adding the new shape went well as far as I can tell, but there are three things to be taken care of before opening a PR:

1. I did not run into problems during my tests but it would feel better if the ```[(...)]``` syntax was approved by a member of the mermaid project :)

2. There are gaps between the node and its connection lines. This can probably be solved by using own calculations instead of dagreD3.intersect.rect().

3. The texts are centered in the shape, which is great but it would look better with more space between the upper ellipse and the first line of text. There is also plenty of free space beneath the last line so that sould not be a problem. I have yet to figure out how to do this.

![cylinder](https://user-images.githubusercontent.com/1912783/71529286-60359400-28e4-11ea-8748-fe98d0960a38.png)

**Comment by GDFaber** [comment]
done
