### ISSUE TITLE
Link is not renderly properly in High Contrast. 

### ISSUE THREAD

**Issue by shpraka** [mermaid-js/mermaid#1186]
**Describe the bug**
Link is not renderly properly in High Contrast. Even in dark theme we can reproduce this. 

**To Reproduce**
1. Go to the [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG5BW01lcm1haWQgbGluayBzdXBwb3J0IGluIEhDXSAtLT4gQlt2aXNpdCBoIGZvcl07Y2xpY2sgQiBcImh0dHBzOi8vd3d3Lmdvb2dsZS5jb21cIiBcIlRoaXMgaXMgYSB0b29sdGlwIGZvciBhIGxpbmtcIiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Expected behavior**
In HCB, the color should be yellow and in HCW it should be blue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46188819/71964185-183b3900-3223-11ea-935e-550de11674e9.png)

**Desktop (please complete the following information):**
OS: [ Windows etc.]
Browser [ chrome, Edge etc]

**Additional context**
Same issue is happening with dark theme as well.

**Comment by batchunag** [comment]
Hi @shpraka @knsv , can I work on this issue if it's still valid for a fix? 
I'd like to confirm the expected behaviour. Is it correct that we'd like to have the link element blue in default theme and yellow in the dark theme as in the screenshots below? 
![HCW](https://user-images.githubusercontent.com/1393728/96960815-484b9280-153e-11eb-942a-089e9812b299.png)
![DarkTheme](https://user-images.githubusercontent.com/1393728/96961449-a5941380-153f-11eb-8333-de56f6f61f7f.png)
Thanks.

**Comment by jgreywolf** [comment]
@batchunag Are you still interested in working on this issue? Let me know and I will assign it

**Comment by batchunag** [comment]
Hi @jgreywolf thanks for the follow-up. Yep, I can look into this.
