### ISSUE TITLE
StateDiagram multiple transitions

### ISSUE THREAD

**Issue by FxIII** [mermaid-js/mermaid#1223]
**Expectation**
As a state diagram editor, 
I want to connect the same two nodes through additional named transitions

**To Reproduce**
```
stateDiagram
	NotFound --> NotFound: Status
        NotFound --> NotFound: Stop
```

**Current behaviour**
The second transition overwrites the previous one.

**Comment by knsv** [comment]
That makes sense! I added multigraph capabilities to stateDiagrams. This will be available from 8.4.7. It looks a but cramped in your example: 
![image](https://user-images.githubusercontent.com/5837277/73388325-51227700-42d2-11ea-95f3-6d6e710bdbb2.png)

This is due to the grade layout mechanism and is hard to fix. It does look good in other examplesthough like the one below:
![image](https://user-images.githubusercontent.com/5837277/73388162-04d73700-42d2-11ea-8b6d-3446dbe00ff7.png)

All in all I think it is worth having it enabled. I hop you agree.
