### ISSUE TITLE
Angular 8, mermaid not working properly

### ISSUE THREAD

**Issue by ghost** [mermaid-js/mermaid#1232]
**Describe the bug**
When rendered, the sequence diagram only shows one arrow and other arrows are mashed up into one string and put into title of the first arrow
**To Reproduce**
Found one in earlier [issue](https://github.com/mermaid-js/mermaid/issues/979) awnser, the stackblitz [here](https://stackblitz.com/edit/angular-markdown-mermaid-7jfvvh?file=src%2Fapp%2Fapp.component.ts)

**Expected behavior**
The mermaid should draw all arrows

**Screenshots**
![image](https://user-images.githubusercontent.com/26432543/73459069-ebd88f80-437e-11ea-85ca-ebec240b9d56.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - 8.3.1

**Comment by Dunning-Kruger** [comment]
@JonasGav The markdown is being parsed by the browser and line endings are being stripped before mermaid process them, resulting in the following markup. One trick is to use a `<pre>` instead of a `<div>`.

Updated stackblitz [here](https://stackblitz.com/edit/angular-markdown-mermaid-7jfvvh?file=src%2Fapp%2Fapp.component.html).

**Comment by jgreywolf** [comment]
@ghost did the information from @IOrlandoni help?
