### ISSUE TITLE
Flowchart click interaction does not occur

### ISSUE THREAD

**Issue by fcnyp** [mermaid-js/mermaid#1294]
When clicking a node with an attached click event in flowchart callback is not triggered. This occurs in the example documentation (https://mermaid-js.github.io/mermaid/#/flowchart) in the "Interaction" section as well as a local instance running 8.4.8. I have tried both the example documentation and local in Firefox and Chrome with the same result.

Expected result:
If clicking "A" in example documentation, an alert should be triggered.
If clicking "A" in local instance, a console log should be triggered.

```
var callback = function(){
    console.log('A callback was triggered');
}
let config = {
    startOnLoad: false,
    flowchart:{
        useMaxWidth: false,
        htmlLabels: true
    },
    securityLevel:'loose',
};
mermaid.mermaidAPI.initialize(config);
```

```
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
```

**Comment by Pepper-Wood** [comment]
The root cause of this issue is that the `callback` function that the element is relying on is not initialized on this page. When I open Google Chrome console on https://mermaid-js.github.io/mermaid/#/flowchart: 
```
typeof callback
> "undefined"
```
I believe this repo is using Docsify to render the documentation pages. The Mermaid diagrams appear because they're being rendered correctly in the markdown file.
Seems like this would be a code change in https://github.com/mermaid-js/mermaid/blob/73cac9525576740976fd9c1947d83c62d4ef4f05/docs/index.html I haven't worked with Docsify before, but it seems promising that initializing the callback command would take place in the init script at the bottom. I'll open a PR later but wanted to share my initial findings.
