### ISSUE TITLE
What state is issue 117 in (ERD diagrams)?

### ISSUE THREAD

**Issue by ElectricLlama** [mermaid-js/mermaid#1338]
I came here from Azure DevOps which includes mermaid diagrams. I want to create an ERD. 

I found this issue but it's not clear what state it's in. It says it's merged but the syntax isn't mentioned in help docs. Also the tag as mentioned in this commit doesn't function. https://github.com/mermaid-js/mermaid/pull/1308/commits/3e76b2374c09e172eef1a00b2a0892b98a526915

In summary, I'd like to help but I am having difficulty understanding the current state of this enahancement

https://github.com/mermaid-js/mermaid/issues/117

**Comment by AceLondon** [comment]
@ElectricLlama it looks like it can be found here: [release/8.5.0](/mermaid-js/mermaid/tree/release/8.5.0)

**Comment by spopida** [comment]
@ElectricLlama , yes @AceLondon is correct - ER Diagrams will be in release 8.5 which I believe is imminent.  The syntax has been modified from the original (unreleased) code, so that it will be compatible with PlantUML.

For example, the following mermaid document...
```
erDiagram
      CUSTOMER }|--|{ DELIVERY-ADDRESS : has
      CUSTOMER ||--o{ ORDER : places 
      CUSTOMER ||..o{ INVOICE : "    "
      INVOICE ||--|{ ORDER : covers
      DELIVERY-ADDRESS ||..o{ ORDER : receives
      ORDER ||--|{ ORDER-ITEM : includes
      PRODUCT-CATEGORY ||..|{ PRODUCT : contains
      PRODUCT ||--o{ ORDER-ITEM : "ordered in"
```

... will render this diagram

![image](https://user-images.githubusercontent.com/19526120/78552386-5682cd00-77ff-11ea-9a41-a2955dea6144.png)

Please note this is a brand new feature, and at the moment only covers the basics - entities and relationships.  It doesn't allow attributes of entities to be included.  Hopefully this will follow in a future release.

**Comment by spopida** [comment]
@ElectricLlama, @AceLondon - as ER Diagrams are now live (including docs), I am closing this issue.  Please feel free to comment further or raise new requests.  I hope you like the new feature.
