### ISSUE TITLE
Will mermaid support a) LaTeX markup  and b) typesetting by LaTeX

### ISSUE THREAD

**Issue by krishnakumarg1984** [mermaid-js/mermaid#1387]
Congratulations on developing this nice project. I am very pleased with mermaid's simple and efficient workflow.

I have two questions about Mermaid and LaTeX integration:

- First is about using LaTeX markup, i.e. can I use mathematical expressions like $\int \cos(x)\, \mathrm{d} x = $sin(x)$ inside blocks/flowcharts/labels etc.? If single one liners are possible, how about the full `amsmath` functionality like `multline`,`align`, `gather`, `split` etc.?
- Second question is about typesetting by `(pdf|xe|lua)latex` (the program). For traditional printed content like static PDF output, nothing beats the typesetting quality of `latex`. Can text and math be typeset by `latex`?

**Comment by knsv** [comment]
Hi!

I am sorry to say that there are no current plats to incorporate LaTeX in mermaid. But who knows? We are always open for good pull requests :)

**Comment by gnzlbg** [comment]
I actually expected this to "just work":

```
graph LR;
  x0(($x_0$))-->x1(($x_1$))
```

but apparently MathJax does not recognize it. It would be very helpful to at least have some instructions on which parts of the source code would need to be modified to handle this (I thought it was as easy as just including the mathjax js script), so that those not very familiar with mermaid could give it a try.

**Comment by krishnakumarg1984** [comment]
Well. `Rmarkdown` etc can process LaTeX markup to render the maths in HTML using `katex`/`mathjax`. This is within the realms of technical possibility just in case anyone is wondering.
