### ISSUE TITLE
Is it possible to add notes on a class diagram?

### ISSUE THREAD

**Issue by project2501** [mermaid-js/mermaid#1414]
Hi,

Notes on a class diagram are very useful to convey some important design details. Unfortunately, I couldn't figure out, how can I add notes on a class diagram. Is it possible at all with mermaid?

Thanks!

**Comment by jgreywolf** [comment]
It is possible. You can add notes to other diagrams, but there is no support for this in classDiagrams as of now.

**Comment by project2501** [comment]
Thank you for replying. Notes on class diagrams are what I need though. 
How should we proceed with the issue? Leave it open to call for contribution, or close it?

**Comment by johnverbiest** [comment]
I'll look into it :)

**Comment by jgreywolf** [comment]
@johnverbiest  Any progress?  :)

**Comment by alexyiangou** [comment]
Hey there!
@jgreywolf If possible I would like to give this a try :slightly_smiling_face:

**Comment by jgreywolf** [comment]
@alexandrosyiangou   Any update on this?

**Comment by kiah2008** [comment]
look forward to this enhancement.

**Comment by goldbergyoni** [comment]
Looking forward

**Comment by ACMCMC** [comment]
Hi, has there been any progress on this issue? I would be very interested in having this feature as well :) @alexandrosyiangou

**Comment by VanKurt** [comment]
The missing notes is the only thing keeping me from migrating from Enterprise Architect to Mermaid. I would love to see this feature 👍

**Comment by DKurilo** [comment]
I created PR to add the way to add notes.
Right now it's very basic notes. Later we can make it better.
Also I don't know if `dagre-d3` is still supported. It is broken for class diagram because of these lines: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/utils.ts#L313, looks like someone forgot to remove them.
But I made it working. Surely it's easier to work on one renderer only. :)
