### ISSUE TITLE
Some node names break the diagrams

### ISSUE THREAD

**Issue by italomaia-bk** [mermaid-js/mermaid#1444]
**Describe the bug**
Tried to have a flowchart node called "end". It breaks flowchart.

**To Reproduce**

```
graph TD
  start --> state
  state --> end
```

**Expected behavior**
Should produce diagram

**Desktop (please complete the following information):**
 - Testted on vscode markdown preview

**Comment by GDFaber** [comment]
Hi @italomaia-bk, this is due to the markup language approach which mermaid is built upon. But you can give the node another id and still use "end" for its caption text: [example in the live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgc3RhcnQgLS0-IHN0YXRlXG4gIHN0YXRlIC0tPiBlbmRub2RlW1wiZW5kXCJdIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0).

**Comment by italomaia-bk** [comment]
Is this limitation documented?

**Comment by GDFaber** [comment]
It should be helpful to have a list in the documentation which includes all the words reserved for syntax for every diagram type.

**Comment by NeilCuzon** [comment]
I submitted a PR for this, but I found that "End" also breaks sequence diagrams.
