### ISSUE TITLE
Add line type beta rendering of flowcharts

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#1466]
Currently support for:

```
===
-.-
```

Is not in place

**Comment by vantoan8x** [comment]
Dear @knsv, 

#### currently mermaid being support:
```
—-
-.-
===
=.= (yet, will support?)

—>
-.->
==>
=.=> (yet, will support?)

```

#### yet support:

```
—x
-.-x
==x
=.=x

—o
-.-o
==o
=.=o

```

and two way of arrow/mark styles. <—>, ...
and all invert direction of arrow.

#### note:
invert direction is not reversed write A —> B alternatted by B —> A, it must be A <— B, because the direct of whole direction of flow chart keep correctly.

Regards.
Tom.
