### ISSUE TITLE
Wrong dependent libraries（entity-decode）

### ISSUE THREAD

**Issue by gitWhatever** [mermaid-js/mermaid#1507]
**Describe the bug**
Whether to install the wrong dependent libraries in 8.5.x's version？the 'entity-decode' library will lead to wrong run times

**Additional context**
entity-decode: https://github.com/shrpne/entity-decode

**Comment by knsv** [comment]
Hi! Could you elaborate a little? 

We need to handle html from the browser before starting our parsing which is why we use this library.

First we used the library he but that was very large so in order to decrease the mermaid bundle size we switched to entity-decode/browser which is much smaller.

Is it too slow?

Thanks,
Knut

**Comment by gitWhatever** [comment]
the 'entity-decode' library's browser version has not been compiled with commonJs or UMD module。if use this library  suggest browser version' code can be compiled。

there is a reason is my old project get error after upgrade the mermaid version because don’t support es module。

**Comment by jesseditson** [comment]
I think I'm encountering the same issue - it seems that the `entity-decode` module is not commonjs compatible. This means that when attempting to use `mermaid` in a jest environment, `entity-decode/browser.js` will cause the compilation to fail (since it has an `export` keyword).

**Comment by sidharthv96** [comment]
entity-decode was removed.
