### ISSUE TITLE
sequence diagram code interpretation not like in other graph types

### ISSUE THREAD

**Issue by michaelgreyskull** [mermaid-js/mermaid#1526]
Dear Devs,

there seems to be a weird behavior when rendering sequence diagrams. While other diagram types, like flowcharts, accept code for labels and nodes, in sequence diagrams this code is not interpreted but printed.

Example:
```
graph TD
	A[Christmas] -->|Get money| B[fa:fa-car Buy Car]
```
This makes a perfect graph including the car symbol.
But:
```
sequenceDiagram
	John-->>Alice: I feel great! [fa:fa-car Car]
```
does not show the symbol but the exact characters `[fa:fa-car Car]`.
Same goes for htmlLabels, esp. `<sub>subtext</sub>` tags.

Am I missing something here or is this behavior intended?

Thanks! (:

**Comment by cmmoran** [comment]
Your observation is correct. Each diagram is an individual component. The syntax (grammar) and how it is parsed is wildly different across diagram types. It would be great to have all of the diagrams share a base grammar for various things like you mentioned. It's definitely doable; it just requires a fair amount of work (read: refactoring) in order to make it so.

Great point though. It is definitely something I could get behind.

**Comment by michaelgreyskull** [comment]
Thank you for your reply and encouragement! I will read about refactoring and see if I can do anything here.

**Comment by jgreywolf** [comment]
There is currently no support for font awesome in sequence diagram. 
Refactoring as suggested here is being worked on via a separate item, but there is no plan to add font-awesome support elsewhere yet
