### ISSUE TITLE
Arrow of class diagram inheritance arrow missing

### ISSUE THREAD

**Issue by lfuhr** [mermaid-js/mermaid#1687]
There are two options. 
* Introduce another arrow like --i> , --[>, --o>  or  --|:> 
* Change the black arrow --|> to be white

What do you think

**Comment by WolfgangFahl** [comment]
see #780

**Comment by WolfgangFahl** [comment]
see https://en.wikipedia.org/wiki/Class_diagram#/media/File:Uml_classes_en.svg
![grafik](https://user-images.githubusercontent.com/1336221/125340179-71bd8000-e352-11eb-88a8-549f738888d2.png)

**Comment by fightinggg** [comment]
> There are two options.
> 
> * Introduce another arrow like --i> , --[>, --o>  or  --|:>
> * Change the black arrow --|> to be white
> 
> What do you think

I think so
Inheritance arraow should fill with white color

**Comment by wouterbeek** [comment]
Yes, Mermaid deviates from most if not all other class diagram visualizations in this regard.

**Comment by mvf** [comment]
The arrow should be _hollow_ (i.e. background color, which isn't necessarily white). For now, I'm using the following workaround in my `config.json`:

```json
{
    "theme": "dark",
    "themeCSS": ".extension { fill: #1c1e1f !important; }"
}
```

Before:
![image](https://user-images.githubusercontent.com/304760/132948470-d2720746-3ff0-45c7-9712-d80a94054b1c.png)

After:
![image](https://user-images.githubusercontent.com/304760/132948449-72fde165-cf6f-474f-8b92-4f829aeffdc0.png)

Unfortunately, one can't use `transparent` because then the arrows look like this:
![image](https://user-images.githubusercontent.com/304760/132948459-60f4afea-3076-4363-96ea-34226a5a8e4f.png)

It would be great if Realization and Association/Dependency arrows could be fixed too. The former have a dotted outline, and the latter have an unorthodox tented appearance instead of being just two solid lines.

**Comment by das-g** [comment]
> The arrow should be _hollow_ (i.e. background color, which isn't necessarily white).

Indeed. This is confirmed by <https://www.uml-diagrams.org/generalization.html>:
> A **generalization** is shown as a line with a hollow triangle as an arrowhead between the symbols representing the involved classifiers. The arrowhead points to the symbol representing the general classifier. […]
>
> ![](https://www.uml-diagrams.org/class-diagrams/class-generalizaion-separate.png)
>
> […]
>
> ![](https://www.uml-diagrams.org/class-diagrams/class-generalizaion-shared.png)

**Comment by michalspano** [comment]
Any updates on this one? I like the tool a lot; it's just this inconsistency makes it harder to use, regarding the solid triangle for **inheritance**.

**Comment by skogsbaer** [comment]
I would really appreciate an fix here. Mermaid is just plain wrong regarding generalization arrows.

**Comment by lfuhr** [comment]
I think we should make a point what solution developers should go for.

Give me a thumbs up here if you think
**--|> should be changed to transparent.**

**Comment by lfuhr** [comment]
Give me a thumbs up here if you think
**it would be better to Introduce another arrow like --i> , --[>, --o> or --|:>**

**Comment by lfuhr** [comment]
Give me a thumbs up here if you think
**It is just fine as it is**

**Comment by WolfgangFahl** [comment]
UML sets the standard so i think this could be a way to avoid further discussion:
![grafik](https://user-images.githubusercontent.com/1336221/204081959-01c39bf1-9b95-4dc2-a9c1-d9b406df6a6b.png)
