### ISSUE TITLE
Cannot get 'Annotations on classes' to work with reference to source

### ISSUE THREAD

**Issue by KlopDesign** [mermaid-js/mermaid#1946]
Hi, thanks at first for the great piece of software!

### Annotations
Following the documentation you can make Annotations (like `<<enumeration>>`) on classes like so:
```html
classDiagram
    class Color{
        <<enumeration>>
        RED
        BLUE
        GREEN
        WHITE
        BLACK
    }   
```

This works in the live editor, but I don't get it working with the reference to source in Visual Studio Code and the Google Chrome browser (MS Edge also doesn't work).

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="mermaid">
    classDiagram
      class Color{
        <<enumeration>>
        RED
        BLUE
        GREEN
        WHITE
        BLACK
      } 
  </div>
 <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
 <script>mermaid.initialize({startOnLoad:true});</script>
</body>
</html>
```
I get the 'Syntax error in graph mermaid version 8.9.2' error instead.

Am I doing something wrong? Or is it some sort of bug?
Thanks in advance!

**Comment by loseth** [comment]
This must be a parser bug, when I add a space between the left double brackets and the annotation text, the syntax error goes away. So try writing << enumeration>> instead of <<enumeration>>.

If you have more than one class annotations you'll have to do the same for the others as well.

I've tried this with Mermaid 9.4.0, imported into an HTML document, and it works with Edge, Chrome, and Safari.

**Comment by KlopDesign** [comment]
Thanks! That solved the issue.
