### ISSUE TITLE
Class diagram - Generic Types working on members not Class itself

### ISSUE THREAD

**Issue by LukeTOBrien** [mermaid-js/mermaid#2173]
Hello chaps!

I have been interested in your project for some time and now I am looking at creating a project using your library.

**Describe the bug**

[Generic type support was added in 2019](https://github.com/mermaid-js/mermaid/pull/1120), it seems to work on the members put not on the class itself.  
This is using your latest live editor:
![upload_modes](https://user-images.githubusercontent.com/16164373/124637990-5817c680-de82-11eb-9733-0cd4575d6681.png)

You can see the generic type is only on the member and not the class.

**To Reproduce**
1. Go to the live editor
2. Choose class diagram example
2. Click on use generic types `~Type~` on both the class and the class member

**Expected behavior**
Generic type should work on both the class members and the class itself.

**Screenshots**
Above

**Comment by LukeTOBrien** [comment]
Hi chaps,

Just wanted to add another use case.  
Sometime when developing I might deal with `generic of generic`, for eg in a web app when deserializing YAML or JSON I deal with a variable of type `List<Dictionary<string, object>>`. so in a diagram I would type this as `+List~Dictionary~string, object~~ Data`:  
Your angle brackets are the wrong way around in this scenario:
![genericofgeneric](https://user-images.githubusercontent.com/16164373/124948261-6ee82580-e008-11eb-895d-b5405c14b501.png)

You might want to cover this use case.

**Comment by thebeard** [comment]
@LukeTOBrien given your initial post, I noticed the same as you. After playing around I realized this happens when the class on which you are trying to add a generic has a link, of any kind, to another class. If you remove the link (for testing purposes), you should see the generic appear.

I now see your comment is more than a year old. Ouch, okay. If anyone has a similar issue that was explained/addressed, it would be great to see a link here.
