### ISSUE TITLE
Crash when using classDiagram with generic + link with a tooltip

### ISSUE THREAD

**Issue by glureau** [mermaid-js/mermaid#2944]
**Describe the bug**
Given a `classDiagram` using a [generic](https://mermaid-js.github.io/mermaid/#/classDiagram?id=generic-types), if a click is defined on it, defining a tooltip for the link will break the render.

**To Reproduce**
1. Go to mermaid.live
2. Paste this code:

```
classDiagram
  class ClassWithGeneric~A~ {
    <<class>>
    +release() Unit
  }
  click ClassWithGeneric~A~ href "https://google.fr" "a tooltip"
```

**Expected behavior**
Class diagram should be generated (not in grey).

**Screenshots**
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7968075/163631899-6e667835-7726-444d-ac92-7973eba839e5.png">

**Code Sample**
[live-editor](https://mermaid.live/edit#pako:eNptj8EKwjAMhl-l5KQo7l6GICo-gIiXXkKbbcWtHWl2EJnPbrfpTQIhf_LxJ3mBjY5Ag7ItpnTyWDN2JqhFq-OU716aCwVib9-Ht3pNY6XKckb2-0VumFrCRKu1ugUvU3NcfLx9_PVpmCploBHpky6KOsa6pV3FBnI3R4AtdMQdepcPnLcakIY6MqBz6ZAfEzZmbugdCp2dl8igK2wTbQEHiddnsKCFB_pB3x-_1PgB-rlXpw) (note that you'll have to add the tooltip manually)

**Desktop (please complete the following information):**
 - OS: MAC Monterey 12.3.1
 - Browser Chrome
 - Version 100

**Comment by jgreywolf** [comment]
@glureau Apologize for the long delay in answering. I thought this was going to be difficult to fix, but as I looked into ti further this weekend I realized where the error lies. When we create a class with a generic we split the name from the type - hence, in order to create a link as you mention you would actually need to do the follow, and then no error shows up:

```
classDiagram
  class ClassWithGeneric~A~ {
    <<class>>
    +release() Unit
  }
  click ClassWithGeneric href "https://google.fr" "a tooltip"
```
This takes care of the crash issue - it looks like the tooltip is not showing in the live editor, so I will look at that aspect right now
