### ISSUE TITLE
Extension support: Does it support customize user’s own type of diagram and the customized syntax for the new diagram

### ISSUE THREAD

**Issue by cdhit** [mermaid-js/mermaid#3182]
The diagram I want is not in the diagram list. I'd like it to support new type of diagram or graph. 

For example, I'd like to customize a wall, I simply put the height and width of the wall, it draws me a wall. 

I'd like a stud in the wall in somewhere offset the beginning of the left side. 

I simply put in the offset value, it draws me a stud next to the left side of the wall.

**Comment by jandrieu** [comment]
Out of curiousity, why was this closed?

Is this possible to do out of the box?

I see directions on how to contribute to mermaid to add to the mermaid deployment, but what's the API for registering a new type of diagram that is entirely defined client-side, without support bundled into the mermaid code?

I ask because I have the same need.
