### ISSUE TITLE
Cannot have Generic of Generics in Class diagram

### ISSUE THREAD

**Issue by mohsenoid** [mermaid-js/mermaid#3287]
**Describe the bug**
In the class diagram we can use ~ to achieve <T> generic types, for instance:
```
classDiagram
  MyInterface: +StateFlow~Int~
```

But we cannot have Generic of generic <T<K>>, for instnace:
```
classDiagram
  MyInterface: +StateFlow~List~Something~~
```

and the result is:
```
+StateFlow<List>Something<>
```

Related to #1120 and #1063

**Comment by DeveloperPaul123** [comment]
Also related, these types of class diagrams with overloads of generic parameters do not render correctly either. 

```
classDiagram

class A~T~ {
    +T value
}

class A~T,N~ {
    
}

class A~int~ {
    
}

A~int~ <|.. A~T~
```

Renders like:

```mermaid
classDiagram

class A~T~ {
    +T value
}

class A~T,N~ {
    
}

class A~int~ {
    
}

A~int~ <|.. A~T~
```

**Comment by sidharthv96** [comment]
You can have `List~Something~T~~ ids`. 

```mermaid
classDiagram
class A {
    List~Something~T~~ ids
}
```

So the issue is only with Class having generic types at the top. It might be a bug with the grammar.

**Comment by BlueDreaux** [comment]
The nested generics is good but this doesn't yet seem to support lists of generics as commonly used for things like Map<K,V>.
Trying to diagram a class member that's a Map of string identifiers to a specific set of function types and the comma separated list of generics seems to give the current implementation a curve ball it didn't expect and it displays tilde's instead of the generics brackets.

Example:
``` ts
class MyDemo<T> {
  private demoFns: Map<string, (s: T) => void>
}
```

``` mermaid
classDiagram
  class MyDemo~T~ {
    #demoFns: Map~string, (s: T) => void~
  }
```

**Comment by jgreywolf** [comment]
> 
> Example:
> 
> ```ts
> class MyDemo<T> {
>   private demoFns: Map<string, (s: T) => void>
> }
> ```
> 
> ```
> classDiagram
>   class MyDemo~T~ {
>     #demoFns: Map~string, (s: T) => void~
>   }
> ```

So you mean specifically when you use a => statement, since the parser trips on the bracket after the equals?

**Comment by BlueDreaux** [comment]
Apologies, I was thinking it was for the lack of generic list support but in testing with a fresh look it seems to handle the list of generics just fine. 

Test:
```ts
class MyDemo<X,Y> {
  private xVector: X
  private yVector: Y
}
```
```mermaid
classDiagram
  class MyDemo~X,Y~ {
    #xVector: X
    #yVector: Y
  }
```

However, in coming up with an example that avoids the js shorthand (thanks for pointing that out) I'm still seeing tilde's instead of brackets in what's generated.
```ts
class MyDemo<X,Y> {
  tests: Map<string,(X,Y): void>
}
```
```mermaid
classDiagram
  class MyDemo~X,Y~ {
    tests: Map~string,(X,Y): void~
  }
```

Furthermore, if I try to express an anonymous object type mapping I get a `Diagram error not found.` error I'm not sure how to begin unraveling.
```ts
class MyDemo<X,Y> {
  tests: Map<string,{X,Y}>
}
```
```mermaid
classDiagram
  class MyDemo~X,Y~ {
    tests: Map~string,{X,Y}~
  }
```

**Comment by jgreywolf** [comment]
The parser is choking on two aspects of this.

1. The curly braces signal a "struct_start"/"struct_end" section, inside of which there should be the class definition with members. 
2. Commas inside of a generic value start/stop

This is going to take a little more time to find the best way to address this
