### ISSUE TITLE
[DevOps] Optimize CI workflows?

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#3497]
**Describe the bug**
The following workflows are run on every PR.

```
E2E / build (16.x) (pull_request) In progress — This check has started...
E2E / build (16.x) (push) In progress — This check has started...
Build / build (16.x) (pull_request) Successful in 1m
Build / build (16.x) (push) Successful in 2m
CodeQL / Analyze (javascript) (pull_request) Successful in 1m
Dependency Review / dependency-review (pull_request) Successful in 5s
Lint / lint (16.x) (pull_request) Successful in 1m
Lint / lint (16.x) (push) Successful in 2m
Static analysis / check tests (pull_request) Successful in 20s
Static analysis / check tests (push) Successful in 20s
Unit Tests / build (16.x) (pull_request) Successful in 2m
Unit Tests / build (16.x) (push) Successful in 2m
Validate PR Labeler Configuration / pr-labeler (pull_request) Successful in 5s
Validate PR Labeler Configuration / pr-labeler (push) Successful in 4s
Code scanning results / CodeQL Successful in 3s — No new or fixed alerts 
```

Looks like we're running almost all workflows twice, on `push` & `pull_request`.
Although it doesn't affect us directly, it's still wasted resources.

**To Reproduce**
Create a PR

**Expected behavior**
Workflows are run once

**Comment by aloisklink** [comment]
This is a pretty well known issue with GitHub.

You normally want workflows to run on `push`, so you can make sure everything works on a testing branch before you make a PR.

However, you also need workflows run on `pull_request`, since if somebody makes a PR from a fork, you can't see their `push` workflow status.

Another thing is that for a PR, the on `push` actions will run on `pull_request-HEAD` in the diagram below.

However, the on `pull_request` actions will run on a temporary merge commit `pull_request-MERGE`. This can result in the `push` action succeeding, but the on `pull_request` action failing (e.g. in case of bad merge or differences on the parent branch).

```mermaid
%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'rotateCommitLabel': false}} }%%
gitGraph
    commit id: "1"
    commit id: "2"
    branch my-pr
    checkout main
    commit id: "3"
    checkout my-pr
    commit id: "4"
    commit id: "5" tag: "pull_request-HEAD"
    checkout main
    merge my-pr tag: "pull_request-MERGE"
```

As long as GitHub Actions is free, I'd recommend keeping both!
