### ISSUE TITLE
White text color prints gray

### ISSUE THREAD

**Issue by Jmuccigr** [mermaid-js/mermaid#3584]
**Describe the bug**
White text in a node prints as gray or black (depending on browser).

**To Reproduce**
See the code below, but basically create a graph where the text `color` is white via css. Print the resulting file. The text won't be white, but a gray (Safari, Firefox) or black (Chromium).

**Expected behavior**
Text should stay white when printed.

**Code Sample**
```
graph
    one -->two

classDef reverse color:white;
class one,two reverse;
```
[live editor](https://mermaid.live/edit#pako:eNo1jrsKwzAMRX_FaE5-wIVOWTt11SJspTH4EWy5oYT8e5U-NImro8vZwRXPYOFRaV0wG52S2YzjVbaCGbOL1NrEs6n85NrYuBJLtdsShC-_8_kyKP9nNIcBEtdEwWv5fhYjyMKJEayunmfqURAwH4pSl3J_ZQdWaucB-upJeAqkWgnsTLFpyj5Iqbev8Mf7eAMjO0K-)

**Desktop (please complete the following information):**

- OS: macOS
- Browsers: chrome, safari, firefox
- Version 9.1.7

**Additional context**
Other colors seem fine, though not gray which changes intensity. Try "gray" instead of white, for example.

**Comment by Yokozuna59** [comment]
Hi @Jmuccigr, thanks for reporting the issue.
I think this originally was because of the [theme](http://mermaid.js.org/config/theming.html#available-themes). Anyway, it appears that it works fine in the latest version:

| Theme | Layout |
|:-----:|:------:|
| `default` | [<img height="200" src="https://github.com/mermaid-js/mermaid/assets/87622592/01d214c5-eaec-4aba-bdbc-493848c66bae"/>](https://mermaid.live/edit#pako:eNpFjz0KwzAMha9iNCcXcKFT1k7dihdhy4nBtoJ_GkrI3avQlmqSnj49nnaw7Ag0zAXXxWQlxZnUOF7bxiabbCPWOpFXhZ5UKinLkYveltDo8l2fJ4PwP0Z0GCBRSRicmO-nsYG2UCIDWlpHHntsBkw-BMXe-P7KFnQrnQboq8NGU0CJlUB7jFXUFfOD-T-TC43L7fOA5ezDDMcbEy5JMg) |
| `neutral` | [<img height="200" src="https://github.com/mermaid-js/mermaid/assets/87622592/e4514458-df55-424d-890f-904f5ffbf86f"/>](https://mermaid.live/edit#pako:eNpFjz0KwzAMha8SNCcXcKFT1k7dihdhK4nBloJ_GkrI3avQlmqSnj49nnZw4gkMzBnXxXKnJUzdMFzrJpYtu4iljDR1mZ6UC3VOomSzLaHS5bs-T3rlf4zq0EOinDB4Nd9PYwt1oUQWjLZMrWaMFiwfimKrcn-xA1Nzox7a6rHSGFBjJTATxqLqivwQ-c_kQ5V8-zzghKcww_EGGwZJSA) |
| `dark` | [<img height="200" src="https://github.com/mermaid-js/mermaid/assets/87622592/f9c4e65c-a290-4266-855d-2c04aac9c932"/>](https://mermaid.live/edit#pako:eNpFjrEOwjAMRH-l8tz-QJCYujKxoSxW4rYRjV05KRWq-u8YAcKTffd8uh2CRAIHo-IyeW5shKnpunPdxLPnMGMpPQ2N0oO0UBNkFnXblCqdvvb7pTX-x5gOLWTSjCla-P4O9lAnyuTB2RpR7x48H8bhWuX65ACu6kotrEvESn1C65TBDTgXUxfkm8j_ppiq6OXTPggPaYTjBSeIR-8) |
| `forest` | [<img height="200" src="https://github.com/mermaid-js/mermaid/assets/87622592/af6826f2-431a-41a6-add9-e2d7189fadec"/>](https://mermaid.live/edit#pako:eNpFjrEOgzAMRH8l8gw_kEqdWDt1q7K4iYFIxEZJKEKIf69RW9XT-fx8uh28BAILQ8Z5dGx0hMm07bWu4tixn7CUjnqT6UW5kPEySbbrGCtdvufzpVH-x6gPDSTKCWPQ8P0MdlBHSuTAqnxiUeX4UA6XKveNPdiaF2pgmQNW6iJqpwS2x6moOyM_RP47hVgl3z7tvXAfBzjeJTdH6A) |
| `base` | [<img height="200" src="https://github.com/mermaid-js/mermaid/assets/87622592/62eb3484-9a12-464d-b68b-1783ab26b29b"/>](https://mermaid.live/edit#pako:eNpFjrEOgzAMRH8l8gw_kEqdWDt1q7K4iYFIxEZJKEKIf69RW9XT-fx8uh28BAILQ8Z5dGx0hMm07bWu4tixn7CUjnqT6UW5kPEySbbrGCtdvufzpVH-x6gPDSTKCWPQ8P0MdlBHSuTAqnxiUeX4UA6XKveNPdiaF2pgmQNW6iJqpwS2x6moOyM_RP47hVgl3z7tvXAfBzjeJTdH6A) |

Please confirm that.

**Comment by Jmuccigr** [comment]
Nope, still prints gray (Safari) or black (FireFox). Even the live editor changes the color when I try to print it.

However I now notice that if I tell the browser to print the background, the color is fine (white), but if I leave that preference unchecked, the color is not white, but gray or black, as originally reported.

**Comment by Yokozuna59** [comment]
@Jmuccigr Could you share some screenshots?

**Comment by Jmuccigr** [comment]
Sure. Here's an animated gif of the print dialog in Safari for the basic mermaid chart I posted above. As I toggle the background, the color of the text changes. Same thing happens in FireFox except the the text is black instead of gray. Of course this persists into the actual printout (or PDF).
![Animated gif showing white background problem](https://github.com/mermaid-js/mermaid/assets/615115/70c41208-807a-4ac3-a596-93cc04046db9)

**Comment by Yokozuna59** [comment]
This does not appear to be a bug to me. Browsers don't allow text in the background to have the same color, so they override the text color to another color to make it visible. The color difference depends on the color selected in the browser settings, so as you stated, Firefox has the black text color as the default, and so on.
 
Possible solutions:

1. Add CSS styles to re-override it again.
2. Modify the browser's preferences to not override the colors.

**Comment by Jmuccigr** [comment]
Could you provide specific instructions about how to do both of those?

Also I don’t quite understand what you’re saying. The browser is happy to show white text on a white background until I try to print it.

**Comment by Yokozuna59** [comment]
- For CSS: Add following the media rule to the page `<style>` tag:

   ```css
   @media print {
      /* styles would be overridden when printing */
   }
   ```

   You need to get the nodes ids then modify their attributes.

- For modifying preferences: https://support.mozilla.org/en-US/questions/1357875#answer-1459422.

---

> Also I don’t quite understand what you’re saying. The browser is happy to show white text on a white background until I try to print it.

In Firefox, the default behavior for printing web pages is to change white text to black when generating a PDF. This behavior is intended to ensure that the content remains readable when printed on a white background, which is common for printed documents.

**Comment by Jmuccigr** [comment]
OK, that's helpful to know about the printing. That seems to be what's going on.

I'm not sure that page on settings helps out though. The Firefox setting (and that isn't my regular browser) is to force one's own colors on the page, which of course gets rid of the white text, or to use the system colors, which in my case gives me a gray background on this page and doesn't impact the printing at all.

I think I'll stick with the Background setting in printing for these cases.
