### ISSUE TITLE
Fill doesn't seem to work for ER Diagrams

### ISSUE THREAD

**Issue by xXMarcinatorXx** [mermaid-js/mermaid#3711]
**Describe the bug**
The fill config for the ER Diagram seems to not be applied

**To Reproduce**
Set ER diagram fill config though a directive or in config

**Expected behavior**
Expected behavior was for the background of an attribute

**Screenshots**

[![](https://mermaid.ink/img/pako:eNp1UDFuwzAM_ArBwvDiIJ61tmu7ZNWiWkwqWBILhRoK2X8vlTRFl5ILSRzvyGu4sCc0SOUluEtxyWYrJ6meskDrTW9LyBd4c4n6YLcZNJ65liv9j7mjHlTbdjhs7bFkwKJmHoYWchADDUb5oESjgdG7so6TIqhYNM3iOcSolcX36JbV4g6awwDHI0RmXiFkYcYJE5Xkgtd3Wlf_Zbhd8ofnaZ7nLg-gd-666Krw6SsvaKRUmrB-eif04wias4tXnZIPwuX1btjNt_0bLyFqSg?type=png)](https://mermaid.live/edit#pako:eNp1UDFuwzAM_ArBwvDiIJ61tmu7ZNWiWkwqWBILhRoK2X8vlTRFl5ILSRzvyGu4sCc0SOUluEtxyWYrJ6meskDrTW9LyBd4c4n6YLcZNJ65liv9j7mjHlTbdjhs7bFkwKJmHoYWchADDUb5oESjgdG7so6TIqhYNM3iOcSolcX36JbV4g6awwDHI0RmXiFkYcYJE5Xkgtd3Wlf_Zbhd8ofnaZ7nLg-gd-666Krw6SsvaKRUmrB-eif04wias4tXnZIPwuX1btjNt_0bLyFqSg)
![image](https://user-images.githubusercontent.com/25668644/197406461-760e5af4-2c56-4b43-aae2-20a3ac36a204.png)

**Code Sample**
[Link](https://mermaid.live/edit#pako:eNp1UDFuwzAM_ArBwvDiIJ61tmu7ZNWiWkwqWBILhRoK2X8vlTRFl5ILSRzvyGu4sCc0SOUluEtxyWYrJ6meskDrTW9LyBd4c4n6YLcZNJ65liv9j7mjHlTbdjhs7bFkwKJmHoYWchADDUb5oESjgdG7so6TIqhYNM3iOcSolcX36JbV4g6awwDHI0RmXiFkYcYJE5Xkgtd3Wlf_Zbhd8ofnaZ7nLg-gd-666Krw6SsvaKRUmrB-eif04wias4tXnZIPwuX1btjNt_0bLyFqSg) to live editor 

**Desktop (please complete the following information):**

- OS: Windows (64-bit)
- Browser Firefox
- Version 106.0.1 (64-bit)

**Additional context**
[Link](https://github.com/mermaid-js/mermaid/blob/22587b99592fde4e1d9ff1338ad01c2680d411de/packages/mermaid/src/defaultConfig.ts#L1000) to the config file where the behavior of fill is defined

**Comment by CalebUsadi** [comment]
I can help with this. The fill is being set as an attribute rather than as a style in the [erRenderer.js](https://github.com/CalebUsadi/mermaid/blob/fc24373667ce5fdf73d5199129db6fb8da3f4053/packages/mermaid/src/diagrams/er/erRenderer.js) file, and is being overridden by subsequent CSS. I have made a small fix on a [branch here](https://github.com/CalebUsadi/mermaid/tree/fix/3711_er_fill_attribute). If this seems unproblematic, I can go through and make the changes uniform. According to the [SVG specification](https://www.w3.org/TR/SVG/styling.html#PresentationAttributes) it's not possible to add an `!important` declaration.
