### ISSUE TITLE
Merge Queue

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4075]
> As of 7 hours ago, the merge queue beta is now public, see https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/
> 
> IMO, it's worth trying it out to avoid semantic merge conflicts.
> 
> So far, in the past few months, I've fixed two of them (this PR and https://github.com/mermaid-js/mermaid/pull/3586), and I'm sure other Mermaid contributors have done the same.
> 
> _Edit:_  Potential issue, we'd need to make most of our CI checks **required**, otherwise the merge queue isn't useful. This means if the CI check fails, the PR can't be merged, unless an admin overrides it.
> 
> _Originally posted by @aloisklink in https://github.com/mermaid-js/mermaid/issues/3985#issuecomment-1423449798_
> 

@knsv @aloisklink we can plan how to integrate merge queues into mermaid here.

**Comment by aloisklink** [comment]
:+1: I wanted to make an issue, but it didn't match any of the current GitHub Issue templates in https://github.com/mermaid-js/mermaid/issues/new/choose, since it wasn't a bug report, or diagram/syntax/theme proposal.

@sidharthv96, is it maybe worth testing the Merge Queue first on a smaller repo, like https://github.com/mermaid-js/mermaid-live-editor?

### Required checks

If we enable Merge Queues, we'd also need to make some of our [GitHub Actions checks **required**](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging).

These are checks that must pass before merging (unless an admin manually overrides it):

![image showing an example **required** CI check on a GitHub PR](https://user-images.githubusercontent.com/19716675/217900922-31b8f573-c02d-4aa7-a80a-54456f52f5e0.png)

In my opinion, we should probably make all of our current CI actions that run on a PR required. Possible exceptions:
  - [**PR Labeler**](https://github.com/mermaid-js/mermaid/blob/68626df0610a18ba53b40ea7b4f4519c5eeb2d99/.github/workflows/pr-labeler-config-validator.yml) and **Validate PR Labeler Configuration**
    - I'm not really sure what these do, but I've never seen them fail, so :shrug: it should be fine to make them **required**.
  - **GitHub Code Scanning / CodeQL**
    - This may sometimes fail due to security false positives. However, I think we can either dismiss these alerts, or get an admin to override the false positive and manually merge.
  - **Link Checker**
    - No longer run on PRs, because it fails too often due to issues with https://twitter.com, and other sites.

In the rare case that CI temporary fails for some reason (e.g. due to GitHub Actions/NPM/Cypress server downtime), the merge queue means that it should be auto-merged once CI passes anyway.

---

Not 100% related, but it might be worth locking down the `develop`/`main` branches so that only @mermaid-js admins can push to it. We have had people push stuff to `develop` accidentally before (see https://github.com/mermaid-js/mermaid/pull/3840#issuecomment-1323276541), and although I've never done it in the @mermaid-js project, I have done it a couple times in other repos.

For minor fixes (e.g. documentation updates), @mermaid-js collaborators can always still make a PR and just merge it themselves (which also has the benefit that GitHub Actions will run on it)

**Comment by aloisklink** [comment]
Looks like the Mermaid repo has signed up for the **Merge queue** beta!! Thanks to whoever added this!

See https://github.com/mermaid-js/mermaid/queue/develop

I'm going to close this issue, but we can comment here/re-open this issue if we have any issues with it.
