### ISSUE TITLE
Gantt test broken

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid#4198]
### Description

In 9.4.2

<img width="568" alt="image" src="https://user-images.githubusercontent.com/10703445/223425398-0f24af3d-c647-49c2-ab12-da00d3242c70.png">

In 10

<img width="890" alt="image" src="https://user-images.githubusercontent.com/10703445/223425449-2d7c862a-61f1-434a-888f-e87cba46d73e.png">

demo says line should be invisible, but it's visible.

### Steps to reproduce

```mermaid
gantt
    title Hide today marker (vertical line should not be visible)
    dateFormat Z
    axisFormat %d/%m
    todayMarker off
    section Section1
    Today: 1, -01:00, 5min
```

**Comment by sidharthv96** [comment]
@aloisklink possibly related to dayjs? But not sure why the behaviour is different between v9 & v10

**Comment by aloisklink** [comment]
I just ran Cypress on commit https://github.com/mermaid-js/mermaid/commit/06640aba06c9faab3adfbe0ed047883b419844b0 (aka the one right before https://github.com/mermaid-js/mermaid/commit/a5db04b01c45a94f235f5d889df8babddfa3069d, where we added `dayjs`), and I'm getting the same diagram, so `dayjs` didn't change anything.

> Cropped from `cypress/snapshots/rendering/gantt.spec.js/Gantt-diagram-should-hide-today-marker.snap.png` in commit https://github.com/mermaid-js/mermaid/commit/06640aba06c9faab3adfbe0ed047883b419844b0:
>
> ![image](https://user-images.githubusercontent.com/19716675/223769779-29fa1e2a-720e-4c02-9856-e7fe7705a1df.png)

The only e2e test snapshot that changed in the switch to `dayjs` for me was the test I mentioned in https://github.com/mermaid-js/mermaid/pull/4153#issue-1600229880, however, the demo line for that test says: "should FAIL..." but it clearly works, so :shrug:

By the way, we should probably make something like a `develop-v9` branch (if we ever do make any more `v9` releases), instead of committing duplicate commits to `master`/`develop`. Otherwise it makes the git history a bit confusing :)

The OpenWRT repo is a good example, since they are always committing backports: https://github.com/openwrt/openwrt
