### ISSUE TITLE
The markdown pdf and gh jekyll pages does not render the mermaid blocks.

### ISSUE THREAD

**Issue by thatbeautifuldream** [mermaid-js/mermaid#4364]
### Description

As you may see the diagram is not generated I've tried changing mermaid server and deploying it to gh pages it has no effect on the same, kindly guide me to fix the error, thanks.

![image](https://user-images.githubusercontent.com/28717686/235450859-14f657e6-5120-4210-baa4-2342e4c5be50.png)

Niether the gh pages deployment seems to have render the diagram, I've used the ```mermaid notation to indicate the diagram code

![image](https://user-images.githubusercontent.com/28717686/235451170-5f21a881-0ef0-46cd-85fe-1516485e1317.png)

### Steps to reproduce

Here is the link to my gh pages [deployment.](https://ghp.milind.live/backend-notes/006_introduction_to_express/001_client_server_architecture_and_rest/)

Here is the [markdown code](https://github.com/thatbeautifuldream/backend-notes/blob/master/006_introduction_to_express/001_client_server_architecture_and_rest/readme.md)

Here is the rendered [pdf](https://github.com/thatbeautifuldream/backend-notes/blob/master/006_introduction_to_express/001_client_server_architecture_and_rest/readme.pdf)  

### Setup

- Mermaid version: 
- Browser and Version: [Chrome, Edge, Firefox]

### Additional Context

- Altough i have fixed it temporarily using the [mermaid cli](https://github.com/mermaid-js/mermaid-cli) , if there exists a solution for markdown pdf kindly help me out.

**Comment by huynhicode** [comment]
Hi @thatbeautifuldream 

You can try installing a VS Code extension called, "[Markdown Preview Mermaid](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)".

I cloned your repo and have the extension enabled.  Was able to view the diagram in the markdown previewer.

![Screenshot 2023-05-01 at 9 06 07 AM](https://user-images.githubusercontent.com/35910788/235484574-0ebd0152-b152-41eb-8178-9b969f47eb10.png)

**Comment by thatbeautifuldream** [comment]
> Hi @thatbeautifuldream
> 
> You can try installing a VS Code extension called, "[Markdown Preview Mermaid](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)".
> 
> I cloned your repo and have the extension enabled. Was able to view the diagram in the markdown previewer.
> 
> ![Screenshot 2023-05-01 at 9 06 07 AM](https://user-images.githubusercontent.com/35910788/235484574-0ebd0152-b152-41eb-8178-9b969f47eb10.png)

Thank you for your reply, i have already tried that but that is not my problem problem is well when markdown-pdf generates the pdf it does not render the mermaid diagrams in the pdf instead it spits out a regular code block.

**Comment by thatbeautifuldream** [comment]
I have found a hack i may illustrate it here for others stuck in simmilar problem.

- To generate the svg files from the embedded mermaid code blocks inside markdown you may use mermaid-cli package, which can be globally installed using npm.

```bash
npm install -g @mermaid-js/mermaid-cli
```

- Transform a markdown file with mermaid diagrams

```bash
mmdc -i readme.md -o readme-out.md
```

This way I am able to genearate a markdown with diagrams that are rendered just as perfect.

**Comment by aloisklink** [comment]
Hi @thatbeautifuldream, [`markdown-pdf`](https://github.com/alanshaw/markdown-pdf) does not support Mermaid by default, see https://github.com/alanshaw/markdown-pdf/issues/177.

As far as I'm aware, the only tool that might help go from Markdown to PDF is [pandoc](https://github.com/jgm/pandoc) with a [mermaid-filter](https://github.com/raghur/mermaid-filter). But using `mermaid-cli` like you mentioned is probably the easiest way of doing things!

For your GitHub pages deployment, whatever tool that you're using to convert Markdown to HTML also needs to support Mermaid. For example, if you're using Jekyll, you may want to use the [jekyll-spaceship plugin](https://github.com/jeffreytse/jekyll-spaceship#4-mermaid-usage), or just embed the following HTML into your Jekyll templates:

```html
    <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
      mermaid.initialize({ startOnLoad: true });
    </script>
```

There is some generic documentation on how to do this here: https://mermaid.js.org/intro/n00b-gettingStarted.html, but you may want to follow a Jekyll specific guide.

---

By the way, I'm going to close this issue, since it's not an issue with the Mermaid project, and it's instead an issue with `markdown-pdf` and jekyll, but feel free to continue to comment here!
