### ISSUE TITLE
Mermaid timeline not working, all other types working

### ISSUE THREAD

**Issue by youarehou** [mermaid-js/mermaid#4417]
### Description

When I enter syntax from mermaid.js.org into my markdown file, there are no problems with any of the diagrams... except for timeline. When I enter the following into my markdown file:
<img width="331" alt="Screen Shot 2023-05-20 at 4 34 31 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/1b6510f5-784d-46e9-8aec-7af44df63cd8">

I see the following error on my site:
<img width="699" alt="Screen Shot 2023-05-20 at 4 33 57 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/907e1d3f-f5ae-44c0-a390-5a65303bff86">

Every other diagram type works fine (i.e. flowchart, user journey, even gitgraph) — except for context, mindmap, and timeline diagrams. They all present the same error (but the rest of the site is served fine).

### Steps to reproduce

1. Using Mac OS 10.12.6, Ruby 2.7.8, Jekyl 4.3.2, Chirpy-starter template theme
2. Site has been served locally and on GitHub pages with multiple pages and theme configurations
3. Saw Mermaid section in [Chirpy theme live demo](https://chirpy.cotes.page/posts/write-a-new-post/#mermaid)
4. Went to existing post and added "mermaid: true" to the bottom of YAML header of markdown file:
5. Successfully added/rendered multiple different types of diagrams (i.e. flowchart, user journey, gitgraph) by copying/pasting syntax from https://mermaid.js.org/ to markdown file body:
6. Tried to copy/paste syntax for last three diagrams listed (i.e. context, mindmap, timeline) from https://mermaid.js.org/ to markdown file body. However, each attempt always resulted in the same error: 

### Successful (flowchart diagram):

<img width="133" alt="Screen Shot 2023-05-20 at 5 44 16 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/3adffdb1-4eb0-48b5-8568-58c368f60fba"><br>

<img width="529" alt="Screen Shot 2023-05-20 at 5 44 31 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/7fb1fbdf-e5a6-4070-8903-f7faf06bb9f6">

### Unsuccessful (timeline diagram):

<img width="331" alt="Screen Shot 2023-05-20 at 4 34 31 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/a9a5930b-6f56-47e6-81a9-95ec7308654b"><br>

<img width="699" alt="Screen Shot 2023-05-20 at 4 33 57 PM" src="https://github.com/mermaid-js/mermaid/assets/109917121/0edda921-87e9-4608-8e4d-17e3f1149237">

### Setup

- Mermaid version: Unknown... whatever comes with the Chirpy theme.
- Browser and Version: Brave [Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (x86_64)](https://brave.com/latest/)

### Additional Context

It's just weird that all Mermaid diagrams function fine (after installing ruby, jekyll, chirpy, etc.) except for the timeline, context, and mindmap ones.

**Comment by aloisklink** [comment]
Hi, timeline diagrams were only added in [Mermaid v9.4.0](https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0).

Mermaid mindmaps were also only added to `mermaid` in [Mermaid v9.4.0](https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0) (previously, you had to enable a `@mermaid-js/mermaid-mindmap` plugin).

I'm unsure why C4Context diagrams are not working, but since it's currently an experimental diagram, it's very likely that the current example diagrams don't work on an older version like Mermaid v9.2.2.

My advice is to update the Chirpy theme to use a newer version of Mermaid! I'm not a Jekyll expert, but maybe a plugin like [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship#readme) might help?

Alternatively, you could try reading the [docs for Mermaid v9.2.2](https://github.com/mermaid-js/mermaid/tree/v9.2.2/docs), and only use features listed in that version.

Closing this since it's not an issue with Mermaid, but you may want to make an issue with the chirpy jekyll theme instead!
