### ISSUE TITLE
Installing @mermaid-js/mermaid-zenuml via npm produces unsupported URL type error

### ISSUE THREAD

**Issue by ReeceHumphreys** [mermaid-js/mermaid#4586]
### Description

Attempting to install `@mermaid-js/mermaid-zenuml` via npm fails with the following error:

```shell
npm i @mermaid-js/mermaid-zenuml
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:>=10.0.0

npm ERR! A complete log of this run can be found in: /XXX/YYY/.npm/_logs/2023-07-03T13_18_42_259Z-debug-0.log
````

### Steps to reproduce

1. Create a fresh directory and use `npm init` to initialize npm in the directory.
2. Install mermaid via `npm i mermaid`
3. Install mermaid-zenuml via `npm i @mermaid-js/mermaid-zenuml`
4. The error should now have appeared.

### Setup

**System information:**

**npm version**: 9.7.2
**OS**: macOS 13.4.1

**Comment by aloisklink** [comment]
The `workspace:` syntax should have been automatically removed when running `pnpm publish`:

> # Publishing workspace packages
> 
> When a workspace package is packed into an archive (whether it's through `pnpm pack` or one of the publish commands like `pnpm publish`), we dynamically replace any `workspace:` dependency by:
>
> - The corresponding version in the target workspace (if you use `workspace:*`, `workspace:~`, or `workspace:^`)
> - The associated semver range (for any other range type)
>
> _Taken from https://pnpm.io/workspaces#publishing-workspace-packages_

I don't know how the Mermaid project published this project, but I guess whoever did publish this used `npm` or `yarn` instead of `pnpm` to publish this.

@sidharthv96, do you have NPM permissions to bump the version on `@mermaid-js/mermaid-zenuml` and then run `pnpm --filter @mermaid-js/mermaid-zenuml publish --dry-run`? If the output looks good, you can run the same command except without the `--dry-run`.

**Comment by aloisklink** [comment]
I've removed the **Status:: Awaiting PR** labels, since it needs somebody with NPM permissions to do this.

It would be nice to have an automated way of publishing the `@mermaid-js/mermaid-zenuml` using GitHub Actions, but IMO, this isn't trivial to do in a mono-repo.

**Comment by sidharthv96** [comment]
Published and verified https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml/v/0.1.1
