### ISSUE TITLE
Arrow heads missing

### ISSUE THREAD

**Issue by GrupaRX7** [mermaid-js/mermaid#4684]
### Description

If I have a problem displaying arrowheads on the chart in Obsidian, can I ask here or only to the author of the Obsidian plugin?

The flowchart Obsidian does not show arrowheads (edit and presentation view).

Can I correct something myself (I am not a programmer) or can I just like it? It would be a pity, as there are times when the arrows are crucial to the graph.

### Steps to reproduce

Syntax below

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/114868497/fdd259f6-89b8-4c01-b70b-56c615d126f6)

### Code Sample

```text
flowchart LR
A-->B
B-->C
```

### Setup

- Mermaid version: Mermaid Tools 0.2.2
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
<img width="240" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/593e4046-585b-4467-abed-bdfbf17d7dcf">

Seems to be working for me. 


```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.0.3
	Operating system: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 22.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	none
```

**Comment by omarkmu** [comment]
Based on the [bug report](https://forum.obsidian.md/t/mermaid-arrows-marks-not-showing/6386) on the Obsidian forum, this is caused by #1318. A workaround has been implemented according to https://github.com/obsidianmd/obsidian-releases/pull/2061#issuecomment-1612350365, but I don't think it's in the public stable release yet—I still see this bug on my end, despite being on the latest non-insider version.

**Comment by jgreywolf** [comment]
Given the comments above, should this issue be closed?

**Comment by jgreywolf** [comment]
Closing based on lack of response/activity
