### ISSUE TITLE
Allow "target=_blank" in the note of classDiagram

### ISSUE THREAD

**Issue by lazyky** [mermaid-js/mermaid#4716]
### Description

There is no attr 'target' in the rendered page. When using classDiagram, links are required to open in new tabs.
```
classDiagram
    class test {
    }
    note for test "<a href='https://mermaid.js.org/' target='_blank'><code>mermaid</code></a>"
```

```mermaid
classDiagram
    class test {
    }
    note for test "<a href='https://mermaid.js.org/' target='_blank'><code>mermaid</code></a>"
```

### Steps to reproduce

Using the live editor: https://mermaid.live/edit#pako:eNpNkMtuhDAMRX8FecMGAYHySMSwapdddVdFqtwhPKZAUDBSp4h_bwZQVW9sH1v3Wl7hqisFAq49zvNzh43BQY6OjZ04pGZy1oNsRxo1KafW5phJKNBpjaovbks0zSIIBmUG7Cr_NvvaNIHrEJpG0cX9-Oxx_HLLc6EIHuZlEWApATw4sb1mN5RArRqUBGHLStW49CRBjptdxYX02328giCzKA-WqUJS5_0gauxnSyccQazwDSJmuR_mYRixjGcszVIP7iAsjHjIo4QlcR4lYRxtHvxobRVCP-VPCY_yOE5YznPGd7n3ffjf86XqSJs_S7W3r-dTH2n7BaVdb7M

### Setup

- Mermaid version: 10.3.0
- Browser and Version: [Chrome 115.0.5790.171]

**Comment by tomperr** [comment]
Related to #3077 
Also, we might update our DOMPurify configuration to allow the `target` attribute as the security issue can be resolved (as explained and discussed [here](https://github.com/cure53/DOMPurify/issues/317))

**Comment by VividhPandey003** [comment]
Hey, this seems to be a very easy issue as to what I have perceived until now. Could you please explain me the issue better if possible. I am new to contribution to such large codebases.

Regards,
Vividh

**Comment by nirname** [comment]
@VividhPandey003
We have a class diagram and we can add a note to a class
```
classDiagram
class test { }
note for test "note about mermaid"
```

A note can have an HTML label in it, which will result as embedded `foreignObject` inside svg.
```
classDiagram
class test { }
note for test "<a href='https://mermaid.js.org/'><code>note about mermaid</code></a>"
```

And if we add `_target` attribute
```
classDiagram
class test { }
note for test "<a href='https://mermaid.js.org/' target='_blank'><code>note about mermaid</code></a>"
```

...rendered element will have an `a` tag inside, but `_target` attribute is missing

```
<a href="https://mermaid.js.org/"><code>note about mermaid</code></a>
```

**Comment by parthesh-tiwari** [comment]
Hello , I want to try some workarounds to solve this issue , I want to deploy it locally and deployment part is not mentioned in the documentation. Where can i find the documentation to deploy it on localhost so i can work on issue.
Thanks!

Best regards,
Parthesh

**Comment by nirname** [comment]
Hello, @parthesh-tiwari

There is a [guide for setting up this locally for development](https://mermaid.js.org/community/development.html#setup-and-launch), let us know if you are looking for something else.

**Comment by parthesh-tiwari** [comment]
Thanks @nirname , will surely let know if i need anything

**Comment by preetsahil** [comment]
The issue is mermaid repo right?
or the mermaid live editor
can you tell

**Comment by dharmik3504** [comment]
hello @nirname 
Can you please advise is this the same repo where there is an error as it seems i wanted to debug **mermaid.esm.mjs** file and I'm not able to find it .

Thanks 
Dharmik

**Comment by nirname** [comment]
Hi @dharmik3504, @preetsahil!

I have not reproduced this issue personally. You still have to find the exact place in the code. Highly likely it is related to this very repository, because live editor is not responsible for the rendering by itself. May be live editor it is not updated to the latest version of Mermaid or something else.

`mermaid.esm.mjs` is minimized version. Debugging minimized version is not the way to go either.

So check it. [Set up the project for local development](https://mermaid.js.org/community/development.html), add or update the example you want to debug at a demo page, open your browser and you will see if it works or not. In case it is not, not let us know, and we will close this issue. Otherwise, feel free to open PR with the changes.

Feel free to ask if you face any problems during deployment process.

**Comment by amnahid** [comment]
how to get it setup in http://localhost:9000/dev/example.html code? I mean where to paste 
```
classDiagram
class test { }
note for test "<a href='https://mermaid.js.org/' target='_blank'><code>note about mermaid</code></a>"
```
in <script type="module"> tag or in <pre id="diagram" class="mermaid"> tag?

**Comment by nirname** [comment]
@amnahid you should edit the code inside `pre` tag with `mermaid` class, and your diagram will be updated. `demo/dev` pages are in `.gitignore`, so it is solely for local experiments

**Comment by amnahid** [comment]
@nirname Yeah this bug is valid, can you assign me to start working on it?

**Comment by nirname** [comment]
@amnahid No need to assign, you can dive in. Sometimes people get stuck while solving task or having some troubles continuing. Lets leave it unassigned so that the others could take their chances on the task. You can open PR, even in the middle of the process and mark it as a draft. If case you write `resolves #issue_number` in the PR description these two will be automatically bonded together.

**Comment by kumar-shobhit** [comment]
@nirname I am a beginner and just started , it would be great if you answer one of my query :
In dev/example.html, at line 19 : import mermaid from '/mermaid.esm.mjs';
I am not able to locate mermaid.esm.mjs in the code base, can you please guide me?

**Comment by amnahid** [comment]
@nirname at first I thought the bug was occuring for dompurify package since it was removing the ```target="_blank"```. But when I commented like the code below of sanitizing function on *mermaid\packages\mermaid\src\diagrams\common\common.ts* file that issue was still there.

```javascript
export const sanitizeText = (text: string, config: MermaidConfig): string => {
      // if (!text) {
          //   return text;
      // }
      // if (config.dompurifyConfig) {
          //   text = DOMPurify.sanitize(sanitizeMore(text, config), config.dompurifyConfig).toString();
      // } else {
          //   text = DOMPurify.sanitize(sanitizeMore(text, config), {
          //     FORBID_TAGS: ['style'],
          //   }).toString();
      // }
  return text;
};
```

Although on the console log ```target="_blank"``` was there but it was not rendering.

<img width="779" alt="Screenshot 2023-10-06 204819" src="https://github.com/mermaid-js/mermaid/assets/52004183/dda514ed-97c0-4417-bb88-00ffbaaaac86">

 Can you explain what is happening there?

**Comment by nirname** [comment]
@amnahid I have not tracked the problem down further than you had

**Comment by nirname** [comment]
@amnahid I have performed debugging and have found out that [removing sanitizeText at v2 class renderer](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/class/classRenderer-v2.ts#L174) was not enough, because it was also called in two other places for [markdown](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/shapes/util.js#L38) and [html](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/shapes/util.js#L46) labels. That means, we have to either alter sanitization function to our needs or rework that label helper as well as rendering function. Actually, some hacks are already [out there](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/common/common.ts#L32) tackling the similar problems for flowchart.

**Comment by amnahid** [comment]
@nirname when I was logging on [markdown](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/shapes/util.js#L38) I was getting nothing (I mean no output) and same as [html](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/shapes/util.js#L46). When I was logging in [decodeEntities\(\)](https://github.com/mermaid-js/mermaid/blob/12a47076cf47aa3876285016d1182d48443afc93/packages/mermaid/src/mermaidAPI.ts#L146) there was no ```target="_blank"```. When I tried to trace where the function is getting called I got a syntext error like this
<img width="457" alt="Screenshot 2023-10-07 185003" src="https://github.com/mermaid-js/mermaid/assets/52004183/49beaee1-51b6-4de4-a764-74287b887233">
<img width="445" alt="Screenshot 2023-10-07 185023" src="https://github.com/mermaid-js/mermaid/assets/52004183/fc3eae31-ea6a-402e-b018-8204ff1ed740">

Can it getting remove some where else?

**Comment by nirname** [comment]
@amnahid  I think you have to debug `sanitizeText`. Put debugger inside and see what happens to `a` tag

**Comment by amnahid** [comment]
@nirname ```target="_blank"``` was removing for this [DOMPurify function](https://github.com/mermaid-js/mermaid/blob/12a47076cf47aa3876285016d1182d48443afc93/packages/mermaid/src/mermaidAPI.ts#L503), but when I solved like below

```javascript
// before fixing
svgCode = DOMPurify.sanitize(svgCode, {
      ALLOWED_ATTR: ['target', 'href'],
      ADD_TAGS: DOMPURIFY_TAGS,
      ADD_ATTR: DOMPURIFY_ATTR,
    });
```
from

```javascript
// after fixing
svgCode = DOMPurify.sanitize(svgCode, {
      ADD_TAGS: DOMPURIFY_TAGS,
      ADD_ATTR: DOMPURIFY_ATTR,
    });
```

Somehow the whole flowchart getting removed. That was occuring for a [if condition](https://github.com/mermaid-js/mermaid/blob/12a47076cf47aa3876285016d1182d48443afc93/packages/mermaid/src/mermaidAPI.ts#L519). Can you give any clue from why or how ```"remove"``` property was in ```node``` on the [code](https://github.com/mermaid-js/mermaid/blob/12a47076cf47aa3876285016d1182d48443afc93/packages/mermaid/src/mermaidAPI.ts#L519).

**Comment by REVERB283** [comment]
I've did the necessary changes but for some reason I'm not able to commit those. It's getting stuck on linting stage, is there anything specific I need to do. 

PFA the video shows the issue is fixed.

https://github.com/mermaid-js/mermaid/assets/23396690/dc7abb57-4d86-4d53-88bb-ed46a3810043

**Comment by nirname** [comment]
@REVERB283 Nicely done. I am afraid I cannot help with linting. You can always call linting step separately from git pre-commit hooks, using `pnpm lint --fix`. Open PR, as soon as you are ready, looking forward for it.

**Comment by REVERB283** [comment]
@nirname any update on the MR review, also can you please assign it to me?

**Comment by nirname** [comment]
@REVERB283 no worries, attached PR is enough, and you can save this issue as a bookmark in GH
