### ISSUE TITLE
class diagram shows nothing with colon(:) or comma(,) inside tilde(~)

### ISSUE THREAD

**Issue by sysescool** [mermaid-js/mermaid#4815]
### Description

```c++
class SurfaceFlinger {
private:
    std::unique_ptr<scheduler::Scheduler> mScheduler;
    std::map<uid_t, Fps> mFrameRateOverridesFromGameManager;
}
```

you can try this:
```
classDiagram
    class SurfaceFlinger1 {
        - std::unique_ptr~scheduler::Scheduler~ mScheduler
    }
```
and this:
```
classDiagram
    class SurfaceFlinger2 {
        - std::map~uid_t, Fps~ mFrameRateOverridesFromGameManager
    }
```
but all of them show nothing

I think is maybe because of colon(:) or comma(,) inside tilde(~).

BTW, how to escape colon and comma in class Diagram ?

I searched Document and issue there is no introduction.

### Steps to reproduce

copy below content to https://mermaid.live
```
classDiagram
    class SurfaceFlinger1 {
        - std::unique_ptr~scheduler::Scheduler~ mScheduler
    }
```
another:
```
classDiagram
    class SurfaceFlinger2 {
        - std::map~uid_t, Fps~ mFrameRateOverridesFromGameManager
    }
```

### Setup

- Mermaid version: v10.3.0
- Browser and Version: Firefox: 113.0.2 (64-bit)

**Comment by sidharthv96** [comment]
This is fixed in [develop](https://mermaid-js.netlify.app/edit#pako:eNo9jr0OwjAMhF8l8lwGVs-IF-gaCVmJ20YkaXHiAVXts9Mf4KZPPvvOM7jRMyC4SKXcAvVCyWaz6ZiYVqUjx_cYcs9yNfNp7rqYUj2i5vBSfkxV1uIG9hpZENsfrib9-bxdoIHEkij4rfgItFAHTmwBN_QkTws273ukdWzf2QFWUW5AJ0-Vv38CdhQLLx_FDUMt). 

<img width="1512" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/63976439-f2d8-4aee-b7f3-a4716a3a4f5c">

<img width="878" alt="image" src="https://github.com/mermaid-js/mermaid/assets/10703445/564b3b7a-d104-48d5-8944-202f208144d4">

Please wait for the next release.
