### ISSUE TITLE
GitGraph orientation example is broken in docs

### ISSUE THREAD

**Issue by sneakers-the-rat** [mermaid-js/mermaid#4885]
### Description

In the documentation, the GitGraph Orientation example showing how to make a graph run `TB` (which is sort of confusing to me, since to me it seems like that should be `LR`) does not actually run `TB`

https://mermaid.js.org/syntax/gitgraph.html#orientation-v10-3-0

### Steps to reproduce

* Go to https://mermaid.js.org/syntax/gitgraph.html#orientation-v10-3-0
* Observe the graph is not `TB`

### Screenshots

<img width="774" alt="Screen Shot 2023-09-28 at 5 17 59 PM" src="https://github.com/mermaid-js/mermaid/assets/12961499/2ff97309-bc3b-4a3d-811b-f156594f0036">

### Code Sample

```text
N/A
```

### Setup

- Mermaid version: Website! Can't tell!
- Browser and Version: Firefox 118.0.1

**Comment by guypursey** [comment]
The documentation is very confusing... I thought that actually every diagram except the one in your screenshot was the wrong way around.

`LR` (or leaving blank) means the branches should run from left to right like this:

```mermaid
gitGraph LR:
    commit
    branch develop
    checkout develop
    commit id:"hello"
    commit id:"world"
    checkout main
    commit
    cherry-pick id:"hello"
```

`TB` means they should run top to bottom, alongside each other like this:

```mermaid
gitGraph TB:
    commit
    branch develop
    checkout develop
    commit id:"hello"
    commit id:"world"
    checkout main
    commit
    cherry-pick id:"hello"
```

The words "lined horizontally" and "lined vertically" are confusing since they could be interpreted either way.

I'd be happy to update the wording in the documentation if I could work out why all the graphs are rendering in `TB` mode instead of just the one that's supposed to.
