### ISSUE TITLE
Export Button Not Working on Safari

### ISSUE THREAD

**Issue by oryx-it** [mermaid-js/mermaid#4917]
### Description

It's impossible to export any diagram in Safari on macOS. Export Button not working. I click on it and nothings happens.

### Steps to reproduce

1. Open a diagram
2. Click on export

### Setup

- Mermaid version: Latest and greatest
- Browser and Version: Version 16.6 (18615.3.12.11.2)

**Comment by Yokozuna59** [comment]
@oryx-it Hi there, looking at the video provided, you should file the issue in @mermaidchart, not here.

I'm not sure why all repositories there are now private. CC @huynhicode

**Comment by huynhicode** [comment]
Thanks @Yokozuna59 

The Mermaid Chart issue tracker repo is public and as @Yokozuna59 mentioned, you can log issues specific to the Mermaid Chart platform there instead of here.

@oryx-it There is a similar issue that has been logged.  Please see [Issue #39](https://github.com/Mermaid-Chart/issue-tracker/issues/39).
