### ISSUE TITLE
`titleTopMargin` option for flowchart does not affect subgraph titles

### ISSUE THREAD

**Issue by zoeyTM** [mermaid-js/mermaid#4935]
### Description

When using subgraphs in a flowchart, there is currently no way to customize the padding around a subgraph's title. Larger diagrams consisting of multiple concurrent subgraphs cause mermaid to render the subgraph titles extremely close to the subgraphs top border, making the graph appear unpolished. 

I hoped that `titleTopMargin` would affect subgraph titles too, but it currently only applies to the main flowchart title. There is no other config option that allows for this specific type of customization either. 

--

The current workaround I've found is to nest subgraphs inside each other to give the illusion of a padded subgraph title, [like in this live editor snippet](https://mermaid.live/edit#pako:eNqNkcFuwjAMhl8l8rlPkNvYduCANGm7NRy82qURqYPcRFOFeHcCK6DCNs0nO_7_T7-cPTSRGCy0IX41HWoyHwsnTlbjKlIOfOpNqSF_bhR3nbksarP-3pBXbpKPMjnNVA-ONyTysqkd1Ne3AoH1zfMb60feUoT1GuM_iKf5uJiPz_dyFnoIkcYSepbAtD4EK1G4GpLGLZ_7m-2OMidMN_mLcfZDBT1rj57KX-1PCwep454d2NIS6taBk0PR5R1h4lfyKSrYFsPAFWBO8X2UBmzSzBfRi8dy0n5SHY6b_6JM), however this comes with its own drawbacks such as the subgraph scaling inconsistently in size and there being a lot of extra empty space everywhere else in the graph as well.

### Steps to reproduce

[Here's a live editor snippet](https://mermaid.live/edit#pako:eNo9kDFvhDAMhf8K8gxSpW7Zetd2YypjFjcxEBUclHNUnRD_vfHlShbnfe_JtryDi57AQNd1liXIQqb5XOKvmzHJoNryw7M8_uNmuKi-5e8p4TY3_b2PPmvSh0ROQuRnpCnvrZZLLVfFxN4ytLBSWjH4Mn5X14LMtJIFU74e04-FtvJztHp77VTSut4Qtx7TFFit1xf1DstH6Y5Z4tedHRhJmVrIm0eh94Bl6xXMiMvtpB8-SEwnpIfs62lc5DFMcPwBW0xlHg) demonstrating a flowchart with a title containing a subgraph that also has a title. The `titleTopMargin` config option has also been set, but it's only affecting the flowchart title, not the subgraph title.

### Screenshots

Screenshot showing the subgraph without the desired padding:
<img width="849" alt="Screen Shot 2023-10-09 at 5 35 30 PM" src="https://github.com/mermaid-js/mermaid/assets/14796043/4e9ada1d-583a-414d-970e-1fc28ead8c1e">

Screenshot showing the workaround solution (still not ideal, but at least the subgraphs title is padded):
<img width="792" alt="Screen Shot 2023-10-09 at 5 13 10 PM" src="https://github.com/mermaid-js/mermaid/assets/14796043/ac463126-d094-4fbc-a426-31ec7a950518">

### Setup

- Mermaid version: v10.5.0
- Browser and Version: Chrome

### Suggested Solutions

Preferred solution would be a new flowchart config option that allows for custom padding around subgraph titles.

An alternate solution would be to apply `titleTopMargin` to subgraph titles as well as the current functionality of applying to the general flowchart title.

**Comment by VishalMCF** [comment]
Hi everyone, which solution suggested by @zoeyTM is suitable?

**Comment by nirname** [comment]
@VishalMCF I think we need a configuration option for margins. You can extend [schema](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/schemas/config.schema.yaml), update types generated from it with with
```
pnpm --filter=mermaid types:build-config
```
and then fix Flowchart renderer.

**Comment by mathbraga** [comment]
@nirname Is adding 2 separate config options (1 for top and 1 for bottom) an ideal solution for this? I figured that in some cases users might want to also add spacing between the subgraph title and its content.

**Comment by nirname** [comment]
@mathbraga I think that 2 configuration options in is enough. It will allow to adjust margins for all the subtitles. May be we should keep it as an object itself:
```
subgraphTitleMargin: {
  top: 10,
  bottom: 20
}
```

or we could use 
```
titleMarting: {
  top: 10,
  bottom, 20
}
```

which would affect graph title too, but we should keep current `titleTopMargin` for backward compatibility anyway

**Comment by mathbraga** [comment]
Hi @nirname, I solved the issue for the generic subgraph, but I'm having trouble when subgraphs have external connections. Was wondering if it's possible to make a PR for only the general case and then create another issue for the external connections variation.

**Comment by nirname** [comment]
@mathbraga Hi! Open PR, let's have a live preview of the change. Your request will be deployed and everyone will be able to see what is going on.

**Comment by zoeyTM** [comment]
@sidharthv96 Can we reopen this issue since the feature PR that closed it got reverted?

**Comment by nirname** [comment]
@zoeyTM I think it has been eventually merged
* Original PR https://github.com/mermaid-js/mermaid/pull/5041
* Revert https://github.com/mermaid-js/mermaid/pull/5197
* Re-revert & fix https://github.com/mermaid-js/mermaid/pull/5205

**Comment by zoeyTM** [comment]
Ah! I missed that, thanks!

**Comment by zoeyTM** [comment]
Any idea when the next release might be that would include the re-revert? @nirname

**Comment by nirname** [comment]
@zoeyTM Not really sure, I am not currently responsible for making releases, maybe @sidharthv96 can respond to this

**Comment by Sascha-Block** [comment]
I want to reinforce this issue from a practical documentation and architecture-design perspective.

I am using Mermaid flowcharts in GitHub Markdown to document how framework components within the [Agile Innovation Framework](https://github.com/Agile-Innovation/Agile-Innovation-Framework) relate to each other. In this context, subgraphs represent semantic system boundaries, not just visual decoration.

That is why the behavior described here is important.

When a title margin option does not apply to subgraph titles consistently, the result is not only an imperfect layout. It weakens the reliability of the diagram as a documentation artifact:
- titles can still collide with contained nodes,
- system boundaries become visually ambiguous,
- and the available configuration behaves less predictably than expected.

For architecture communication, this matters. Grouping, naming, and containment are part of the model itself. If these semantics are visually degraded, the diagram no longer communicates the intended hierarchy with sufficient clarity.

This is particularly relevant for common real-world use cases:
- GitHub-native Mermaid rendering,
- logical grouping through subgraphs,
- multi-word or multi-line labels for actual system names.

From my perspective, a robust solution should ensure at least one of the following:
1. configuration options such as title margins also affect subgraph titles reliably,
2. the layout engine reserves vertical space for subgraph titles before placing child nodes,
3. multiline subgraph titles are handled consistently and predictably,
4. the title area of a subgraph is protected from overlap by design.

In transparent and auditable software documentation, structure must remain legible. Otherwise, the diagram stops being a reliable communication artifact and becomes a workaround.

Thanks for opening this issue — I can confirm that it reflects a real documentation problem, not just an edge case.

**Comment by knsv** [comment]
@Sascha-Block A fix for this was merged a long time ago. Are you saying we should open a new bug? I suppose the issue #7264 that you commented on will resolve this as well.
