### ISSUE TITLE
gitGraph support parallel commit

### ISSUE THREAD

**Issue by ppggff** [mermaid-js/mermaid#5114]
### Description

Consider following diagram:
```
gitGraph
    commit
    commit
    branch develop
    checkout develop
    commit
    commit
    checkout main
    commit
    commit
```
```mermaid
gitGraph
    commit
    commit
    branch develop
    checkout develop
    commit
    commit
    checkout main
    commit
    commit
```

The last two commits in the main branch are committed after the two in the develop branch.
Is there a way to show them as parallel commits?

Such as:

<img width="508" alt="Screenshot 2023-12-05 at 14 35 06" src="https://github.com/mermaid-js/mermaid/assets/2892417/02a2ef42-f33b-4a74-8b01-7d76af058538">

May be add a option to the checkout command?

### Steps to reproduce

as above

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment]
I think that is intentional, as the commit order shows the temporal data. Most of the auto-generated graphs follow the same design. It is possible to draw it like this if we switch branches. 

```mermaid
gitGraph
    commit
    commit
    branch develop
    checkout develop
    commit
    checkout main
    commit
    checkout develop
    commit
    checkout main
    commit
```

Adding a parameter to checkout is one option, but if someone needs the entire graph to have parallel commits, it might become cumbersome. We could also introduce a config option `config.git.parallelCommits` to apply the style to the complete graph. 

The config option should be the first step, before we make any changes to the grammar.

**Comment by ppggff** [comment]
Thanks, my original user case for this parallel commit is to:
* describe the development of a series of events, as a time line
* there are multiple timelines because events may change under different situation 

Since is a join of multiple timelines, I hope the event points in different timelines to be independent.

Maybe we could control the order between commit in different branch, such as: `commit id "a" before/after "b"`.
