### ISSUE TITLE
why not   LR model and  TB mode both exist  in same graph

### ISSUE THREAD

**Issue by liujichao-ljc** [mermaid-js/mermaid#561]
i want to make LR model and  TB mode work in same graph some thing like this:
![1234](https://user-images.githubusercontent.com/26374677/29411226-7bb4972c-8386-11e7-814d-42435844b7f9.jpg)

may be codeing like this:

```mermaid
graph TB
A --> B
B --> C
subgraph aa 
graph LR
B --> D
D --> E
end
```

**Comment by vikram-rawat** [comment]
Me too have already opened a request for providing multiple direction on a single graph or adding 2 different graphs with a node.

**Comment by superstar1128** [comment]
Why this issue is not fixed?
This library is not updated anymore?
We don't need to use this library?

**Comment by tylerlong** [comment]
flowchart layout is powered by https://github.com/dagrejs/dagre/wiki#configuring-the-layout

Not sure this is supported in upstream project.

**Comment by tcqiuyu** [comment]
I wondered if this issue still exists. I encountered the same situation as well:(

**Comment by Logerfo** [comment]
I'm interested.

**Comment by knsv** [comment]
I would like to se some solution to this but this is hard due to the reason described above that the layout engine does not support this.

I could see a way to get subgraphs function as their own little graphs with their own directions but then linking to individual nodes from in one subgraph to a node in another subgraph would not be possible. Linking from subgraphs to subgraphs would work though. Also see #1091

**Comment by GDFaber** [comment]
I'm closing this issue in favour of #1265.
