### ISSUE TITLE
Class diagram for generic types

### ISSUE THREAD

**Issue by thekalinga** [mermaid-js/mermaid#770]
If I try to enter this, the tool is generating empty diagram. In java generics are represented by `ContainerType<ElementType>` format. As soon as `ContainerType<E` is typed, the tools is not showing any output. Must be a bug

Try with the following input to reproduce the error

```java
ReactiveHttpInputMessage : Flux<DataBuffer> getBody()
```

**Comment by Dunning-Kruger** [comment]
If anyone's working on this... also, check this very similar one: #656

**Comment by jgreywolf** [comment]
As far as I can tell this is no longer an issue with 8.4.1.  @thekalinga can you validate that what I tried matches what you are trying? [Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBTaGFwZXtcblJlYWN0aXZlSHR0cElucHV0TWVzc2FnZSA6IEZsdXg8RGF0YUJ1ZmZlcj4gZ2V0Qm9keSgpXG59XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

**Comment by jgreywolf** [comment]
Small clarification, looks like you can do this in for objects _inside_ of a class (property/method), but not the class level itself.  Since there is another issue raised that is specifically regarding class level generics (https://github.com/mermaid-js/mermaid/issues/1063) should this be closed in favor of that issue?

**Comment by chris579** [comment]
Right, this issue does not longer exist and for class level generics there is #1063
