### ISSUE TITLE
Linking to multiple nodes

### ISSUE THREAD

**Issue by notramo** [mermaid-js/mermaid#834]
```mermaid
A --> B
A --> C
A --> D
B --> C
B --> D
B --> A
A --> E
B --> E
C --> E
D --> E
```
```mermaid
A --> B, C, D
B --> C, D, A
A, B, C, D --> E
```

**Comment by Dunning-Kruger** [comment]
Hey @ThePenguin1140, are you still working on this? Anything we can help you with?

**Comment by jgreywolf** [comment]
Should this be closed as duplicate of #916 ?

**Comment by Dunning-Kruger** [comment]
@jgreywolf I believe they are different. One allows for one node to be linked to multiple. The other allows for multiple to be chained. `A -> B; A -> C` vs `A -> B; B -> C`

**Comment by jgreywolf** [comment]
You are right. My bad

**Comment by knsv** [comment]
There is a non obvious issue with the syntax here. The problem is that , is a valid character in the node id definition. This is unfortunate. The id statement should have been made strict alphaNum and life would be much easier.

As it is I am reluctant to do grammar changes that break existing diagrams out there.

I think we need to find another separator, maybe space or |
